services:
  redis:
    container_name: ${COMPOSE_PROJECT_NAME}-server
    image: ${REDIS_IMAGE}:${REDIS_TAG}
    restart: always
    volumes:
      - data:/data/db
      - logs:/data/logs
    ports:
      - ${REDIS_PORT}:6379
    environment:
      - CONTAINER_NAME=${COMPOSE_PROJECT_NAME}-server
      - TIMEZONE=${TIMEZONE}
      - ENABLE_LOGS=${ENABLE_LOGS}
      - LOG_LEVEL=${LOG_LEVEL}
      - REDIS_PASS=${REDIS_PASS}

  insight:
    container_name: ${COMPOSE_PROJECT_NAME}-insight
    image: ${INSIGHT_IMAGE}:${INSIGHT_TAG}
    restart: always
    depends_on:
      - redis
    environment:
      RI_APP_HOST: 0.0.0.0
      RI_APP_PORT: ${INSIGHT_PORT}
      RI_LOG_LEVEL: ${RI_LOG_LEVEL}
      RI_FILES_LOGGER: ${RI_FILES_LOGGER}
      RI_STDOUT_LOGGER: ${RI_STDOUT_LOGGER}
    volumes:
      - insight:/data
    labels:
      - "traefik.enable=true"
      # Redirecciona HTTP -> HTTPS
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.rule=Host(`${INSIGHT_DOMAIN}`) || Host(`www.${INSIGHT_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.middlewares=${COMPOSE_PROJECT_NAME}-https-redirect"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-https-redirect.redirectscheme.scheme=https"
      # HTTPS (con SSL automático)
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${INSIGHT_DOMAIN}`) || Host(`www.${INSIGHT_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt"
      # Servicio backend Rates API
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=5540"      
      
volumes:
  data:
  logs:
  insight:

networks:
  default:
    name: ${NETWORK}
    external: true
