version: '3'

services:
  redis:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: ${REDIS_IMAGE}:${REDIS_TAG}
    volumes:
      - redis:/var/lib/redis/data:rw
    restart: always
    command: [redis-server, --save, '60', '10000', --loglevel, 'notice', --timeout, '0', --tcp-keepalive, '300', --databases, '16', --maxmemory, '1024mb', --maxmemory-policy, 'allkeys-lru', --rdbchecksum, 'no']
    ports:
    - ${REDIS_PORT}:6379
    environment:
      - TZ=America/Santo_Domingo
      - REDIS_AOF_ENABLED=yes
      - REDIS_IO_THREADS=4
      - REDIS_IO_THREADS_DO_READS=true
      - REDIS_REPLICATION_MODE=master
      - ENABLE_OVERCOMMIT_MEMORY=true

volumes:
  redis:

networks:
  default:
    name: ${NETWORK}
    external: true
