version: '3'

services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: ${POSTGRES_IMAGE}:${POSTGRES_TAG}
    ports:
    - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      #POSTGRES_INITDB_ARGS: odoo -i base -d ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: -p ${POSTGRES_PORT}
    restart: unless-stopped

  odoo:
    container_name: ${ODOO_CONTAINER_NAME}
    image: ${ODOO_IMAGE}:${ODOO_TAG}
    restart: unless-stopped
    links:
      - postgres:postgres
    ports:
      - "${ODOO_PORT}:8069"
      - "${CHAT_PORT}:8072" # live chat
    expose:
      - "${ODOO_PORT}:8069"
      - "${CHAT_PORT}:8072" # live chat
    tty: true
    volumes:
      - extra-addons:/mnt/extra-addons
    command: -- --dev=reload
    environment:
      HOST: ${POSTGRES_CONTAINER_NAME}
      PORT: ${POSTGRES_PORT}
      USER: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
      VIRTUAL_PORT: 8069
      VIRTUAL_HOST: ${SUBDOMAIN}.${DOMAIN},www.${SUBDOMAIN}.${DOMAIN}
      LETSENCRYPT_HOST: ${SUBDOMAIN}.${DOMAIN},www.${SUBDOMAIN}.${DOMAIN}

volumes:
  postgres-db:
  extra-addons:

networks:
  default:
    name: ${NETWORK}
    external: true
