services:
  android:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${ANDROID_IMAGE}:${ANDROID_TAG}
    restart: always
    devices:
      - /dev/kvm
    environment:
      EMULATOR_DEVICE: ${EMULATOR_DEVICE}
      WEB_VNC: true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${NETWORK:-proxy}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.middlewares=${COMPOSE_PROJECT_NAME}-https-redirect"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=${TRAEFIK_CERT_RESOLVER:-letsencrypt}"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=6080"
    volumes:
      - data:/home/androidusr
      
volumes:
  data:

networks:
  default:
    name: ${NETWORK}
    external: true
