version: '3'

services:
  gitlab-ce:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    hostname: ${GITLAB_HOSTNAME}
    image: ${GITLAB_CE_IMAGE}:${GITLAB_CE_TAG}
    restart: always
    environment:
      TZ: ${TZ}
      # VIRTUAL_HOST: ${GITLAB_HOST},${GITLAB_REGISTRY},${GITLAB_PAGES}
      # LETSENCRYPT_HOST: ${GITLAB_HOST},${GITLAB_REGISTRY},${GITLAB_PAGES}
      SSH_HOST: ${GITLAB_HOST}
      SSH_PORT: ${GITLAB_CE_SSH_PORT}
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${GITLAB_HOST}'
        registry_external_url 'https://${GITLAB_REGISTRY}'
        pages_external_url 'https://${GITLAB_PAGES}'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        registry_nginx['listen_port'] = 80
        registry_nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {  "X-Forwarded-Proto" => "https", "X-Forwarded-Ssl" => "on" }
        gitlab_pages['enable'] = true
        pages_nginx['listen_port'] = 80
        pages_nginx['listen_https'] = false
        gitlab_pages['log_directory'] = "/var/log/gitlab/gitlab-pages"
        nginx['client_max_body_size'] = "0"
        gitlab_rails['time_zone'] = '${TZ}'
        gitlab_rails['smtp_enable'] = ${GITLAB_SMTP_ENABLE}
        gitlab_rails['smtp_address'] = "${GITLAB_SMTP_HOST}"
        gitlab_rails['smtp_port'] = ${GITLAB_SMTP_PORT}
        gitlab_rails['smtp_user_name'] = "${GITLAB_SMTP_USER_NAME}"
        gitlab_rails['smtp_password'] = "${GITLAB_SMTP_PASSWORD}"
        gitlab_rails['smtp_domain'] = "${GITLAB_DOMAIN}"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = false
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['gitlab_email_from'] = "${GITLAB_SMTP_USER_NAME}"
        gitlab_rails['gitlab_email_reply_to'] = "${GITLAB_SMTP_USER_NAME}"  
        # Add any other gitlab.rb configuration here, each on its own line
        prometheus_monitoring['enable'] = false
        sidekiq['concurrency'] = 2
        postgresql['shared_buffers'] = "256MB"
        manage_accounts['enable'] = true
        user['username'] = 'git'
        user['group'] = 'git'
        user['uid'] = 1234
        user['gid'] = 1234
    ports:
#      - "${GITLAB_CE_SSH_PORT}:22"
      - "${GITLAB_CE_REGISTRY_PORT}:5000"
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
    shm_size: '256m'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${NETWORK}"
      # Redirecciona HTTP -> HTTPS
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.rule=Host(`${GITLAB_HOST}`) || Host(`${GITLAB_REGISTRY}`) || Host(`${GITLAB_PAGES}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.middlewares=${COMPOSE_PROJECT_NAME}-https-redirect"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-https-redirect.redirectscheme.scheme=https"
      # HTTPS (con SSL automático)
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${GITLAB_HOST}`) || Host(`${GITLAB_REGISTRY}`) || Host(`${GITLAB_PAGES}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt"
      # Servicio backend GitLab
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"

volumes:
  config:
  logs:
  data:

networks:
  default:
    name: ${NETWORK}
    external: true