version: '3'

services:
  windows:
    container_name: ${COMPOSE_PROJECT_NAME}-${WINDOWS_VERSION}
    image: dockurr/windows
    restart: on-failure
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
      - /var/win:/storage
    environment:
      MANUAL: ${MANUAL}
      CPU_CORES: ${CPU_CORES}
      RAM_SIZE: ${RAM_SIZE}
      DISK_SIZE: ${DISK_SIZE}
      VERSION: ${WINDOWS_VERSION}
      # VIRTUAL_PORT: 8006
      # VIRTUAL_HOST: ${DOMAIN}
      # LETSENCRYPT_HOST: ${DOMAIN}

networks:
  default:
    name: ${NETWORK}
    external: true
