version: '3'

services:
  windows:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${WINDOWS_IMAGE}:${WINDOWS_TAG}
    restart: unless-stopped
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m
    environment:
      MANUAL: ${MANUAL_INSTALLATION}
      CPU_CORES: ${CPU_CORES}
      RAM_SIZE: ${RAM_SIZE}
      DISK_SIZE: ${DISK_SIZE}
      VERSION: ${VERSION}
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
      LANGUAGE: ${LANGUAGE}
      REGION: ${REGION}
      KEYBOARD: ${KEYBOARD}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${NETWORK:-proxy}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.rule=Host(`${URL}`) || Host(`www.${URL}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.middlewares=${COMPOSE_PROJECT_NAME}-https-redirect"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${URL}`) || Host(`www.${URL}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=${TRAEFIK_CERT_RESOLVER:-letsencrypt}"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8006"
    volumes:
      - win_data:/storage

volumes:
  win_data:

networks:
  default:
    name: ${NETWORK}
    external: true
