version: "3"
services:
  runner:
    image: ${GITEA_ACT_RUNNER_IMAGE}:${GITEA_ACT_RUNNER_TAG}
    restart: always
    command: act_runner generate-config > /data/config.yaml
    environment:
      CONFIG_FILE: /data/config.yaml
      GITEA_INSTANCE_URL: "${GITEA_INSTANCE_URL}"
      GITEA_RUNNER_REGISTRATION_TOKEN: "${GITEA_RUNNER_REGISTRATION_TOKEN}"
      GITEA_RUNNER_NAME: ${RUNNER_NAME}
      GITEA_RUNNER_LABELS: ${RUNNER_LABELS}
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  data:

networks:
  default:
    name: ${NETWORK}
    external: true
