version: '3'

services:
  postgresql-server:
    container_name: ${COMPOSE_PROJECT_NAME}-postgresql
    image: ${POSTGRES_IMAGE}:${POSTGRES_TAG}
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  zabbix-server:
    container_name: ${COMPOSE_PROJECT_NAME}-server
    image: ${ZABBIX_SERVER_IMAGE}:${ZABBIX_SERVER_TAG}
    restart: always
    depends_on:
      - postgresql-server
    # links:
    #   - mysql-server:mysql-server
    environment:
      DB_SERVER_HOST: ${COMPOSE_PROJECT_NAME}-postgresql
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "10051:10051"
    volumes:
      - zabbix-server-data:/var/lib/zabbix
      - zabbix-snmptraps-data:/var/lib/zabbix/snmptraps
      - zabbix-export-data:/var/lib/zabbix/export

  zabbix-web-nginx-pgsql:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    image: ${ZABBIX_WEB_IMAGE}:${ZABBIX_WEB_TAG}
    restart: always
    depends_on:
      - postgresql-server
      - zabbix-server
    environment:
      DB_SERVER_HOST: ${COMPOSE_PROJECT_NAME}-postgresql
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ZBX_SERVER_HOST: ${COMPOSE_PROJECT_NAME}-server
      PHP_TZ: ${PHP_TZ}
      VIRTUAL_PORT: 10051
      VIRTUAL_HOST: ${DOMAIN},www.${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN},www.${DOMAIN}
    # ports:
    #   - "${ZABBIX_FRONTEND_PORT}:8080"
    volumes:
      - zabbix-web-data:/usr/share/zabbix

volumes:
  postgresql-data:
  zabbix-server-data:
  zabbix-snmptraps-data:
  zabbix-export-data:
  zabbix-web-data:

networks:
  default:
    name: ${NETWORK}
    external: true
