version: '3'

services:
  postgresql-server:
    container_name: ${COMPOSE_PROJECT_NAME}-postgresql
    image: ${POSTGRES_IMAGE}:${POSTGRES_TAG}
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  zabbix-server:
    container_name: ${COMPOSE_PROJECT_NAME}-server
    image: ${ZABBIX_SERVER_IMAGE}:${ZABBIX_SERVER_TAG}
    restart: always
    depends_on:
      - postgresql-server
    links:
      - postgresql-server:postgresql-server
    environment:
      DB_SERVER_HOST: ${COMPOSE_PROJECT_NAME}-postgresql
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ZBX_TIMEOUT: 10
    ports:
      - "10051:10051"
    # volumes:
    #   - zabbix-server-data:/var/lib/zabbix
    #   - zabbix-snmptraps-data:/var/lib/zabbix/snmptraps
    #   - zabbix-export-data:/var/lib/zabbix/export

  zabbix-frontend:
    container_name: ${COMPOSE_PROJECT_NAME}-frontend
    image: ${ZABBIX_WEB_IMAGE}:${ZABBIX_WEB_TAG}
    restart: always
    depends_on:
      - postgresql-server
      - zabbix-server
    ports:
      - "8090:8080"
    environment:
      DB_SERVER_HOST: ${COMPOSE_PROJECT_NAME}-postgresql
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ZBX_SERVER_HOST: ${COMPOSE_PROJECT_NAME}-server
      ZBX_SERVER_PORT: 10051
      PHP_TZ: ${PHP_TZ}
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: ${DOMAIN},www.${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN},www.${DOMAIN}
    # volumes:
    #   - zabbix-web-data:/usr/share/zabbix

  zabbix-agent:   # Zabbix agent service that tracks usage and send to zabbix server
    container_name: ${COMPOSE_PROJECT_NAME}-agent
    image: zabbix/zabbix-agent:latest
    restart: always
    privileged: true   #access mode for allowing resource access
    depends_on:
      - zabbix-server
    environment:
      - ZBX_HOSTNAME: ${COMPOSE_PROJECT_NAME}-server
      - ZBX_SERVER_HOST: ${COMPOSE_PROJECT_NAME}-server #the IP/Dns of Zabbix server
    volumes:
      - zabbix-agent:/etc/zabbix/

volumes:
  postgresql-data:
  zabbix-server:
  zabbix-agent:

networks:
  default:
    name: ${NETWORK}
    external: true
