version: '3'

services:
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-mariadb
    image: ${MARIADB_IMAGE}:${MARIADB_TAG}
    volumes:
      - speedtest-db:/var/lib/mysql
    restart: always
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_RANDOM_ROOT_PASSWORD: true

  speedtest:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${SPEED_TEST_TRACKER_IMAGE}:${SPEED_TEST_TRACKER_TAG}
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - speedtest-config:/config
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      APP_NAME: ${APP_NAME}
      APP_KEY: ${APP_KEY}
      APP_URL: https://${URL_DOMAIN}
      DB_CONNECTION: mariadb
      DB_HOST: ${COMPOSE_PROJECT_NAME}-mariadb
      DB_PORT: 3306
      DB_DATABASE: ${MARIADB_DATABASE}
      DB_USERNAME: ${MARIADB_USER}
      DB_PASSWORD: ${MARIADB_PASSWORD}
      PRUNE_RESULTS_OLDER_THAN: ${PRUNE_RESULTS_OLDER_THAN}
      CHART_DATETIME_FORMAT: ${CHART_DATETIME_FORMAT}
      DATETIME_FORMAT: ${DATETIME_FORMAT}
      SPEEDTEST_SCHEDULE: ${SPEEDTEST_SCHEDULE}
      SPEEDTEST_SERVERS: ${SPEEDTEST_SERVERS}
      APP_TIMEZONE: ${APP_TIMEZONE}
      DISPLAY_TIMEZONE: ${DISPLAY_TIMEZONE}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${NETWORK}"
      # Redirecciona HTTP -> HTTPS
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.rule=Host(`${URL_DOMAIN}`) || Host(`www.${URL_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.middlewares=${COMPOSE_PROJECT_NAME}-https-redirect"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-https-redirect.redirectscheme.scheme=https"
      # HTTPS (con SSL automático)
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${URL_DOMAIN}`) || Host(`www.${URL_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt"
      # Servicio backend Vaultwarden
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"
    healthcheck:
        test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
        interval: 5s
        retries: 3
        timeout: 5s

      
volumes:
  speedtest-db:
  speedtest-config:

networks:
  default:
    name: ${NETWORK}
    external: true
