version: '3'

services:
  speedtest:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${SPEED_TEST_TRACKER_IMAGE}:${SPEED_TEST_TRACKER_TAG}
    restart: unless-stopped
    volumes:
      - speedtest-config:/config
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      APP_NAME: ${APP_NAME}
      APP_KEY: ${APP_KEY}
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      APP_URL: https://${URL_DOMAIN}
      DB_CONNECTION: sqlite
      PRUNE_RESULTS_OLDER_THAN: ${PRUNE_RESULTS_OLDER_THAN}
      CHART_BEGIN_AT_ZERO: ${CHART_BEGIN_AT_ZERO}
      CHART_DATETIME_FORMAT: ${CHART_DATETIME_FORMAT}
      DATETIME_FORMAT: ${DATETIME_FORMAT}
      DISPLAY_TIMEZONE: ${DISPLAY_TIMEZONE}
      SPEEDTEST_SCHEDULE: ${SPEEDTEST_SCHEDULE}
      SPEEDTEST_SERVERS: ${SPEEDTEST_SERVERS}
      APP_TIMEZONE: ${APP_TIMEZONE}

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${NETWORK}"
      # Redirecciona HTTP -> HTTPS
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.rule=Host(`${URL_DOMAIN}`) || Host(`www.${URL_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.middlewares=${COMPOSE_PROJECT_NAME}-https-redirect"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-https-redirect.redirectscheme.scheme=https"
      # HTTPS (con SSL automático)
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${URL_DOMAIN}`) || Host(`www.${URL_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt"
      # Servicio backend Vaultwarden
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"

volumes:
  speedtest-config:

networks:
  default:
    name: ${NETWORK}
    external: true
