services:
  drone:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${DRONE_IMAGE}:${DRONE_TAG}
    restart: always
    volumes:
      - data:/data
    environment:
      DRONE_GITEA_SERVER: ${DRONE_GITEA_SERVER}
      DRONE_GITEA_CLIENT_ID: ${DRONE_GITEA_CLIENT_ID}
      DRONE_GITEA_CLIENT_SECRET: ${DRONE_GITEA_CLIENT_SECRET}
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_SERVER_HOST: ${DRONE_SERVER_HOST}
      DRONE_SERVER_PROTO: ${DRONE_SERVER_PROTO}
      VIRTUAL_HOST: ${DRONE_DOMAIN}
      LETSENCRYPT_HOST: ${DRONE_DOMAIN}

volumes:
  data:

networks:
  default:
    name: ${NETWORK}
    external: true
