services:
  mariadb:
    container_name: ${COMPOSE_PROJECT_NAME}-mariadb
    image: ${MARIADB_IMAGE}:${MARIADB_TAG}
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      TIMEZONE: ${TIMEZONE}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}

  phpmyadmin:
    container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
    image: ${PHPMYADMIN_IMAGE}:${PHPMYADMIN_TAG}
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      PMA_HOST: ${COMPOSE_PROJECT_NAME}-mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1 # To allow fill db credentials
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${NETWORK}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-phpmyadmin-http.rule=Host(`${PHPMYADMIN_DOMAIN}`) || Host(`www.${PHPMYADMIN_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-phpmyadmin-http.entrypoints=web"      
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-phpmyadmin.rule=Host(`${PHPMYADMIN_DOMAIN}`) || Host(`www.${PHPMYADMIN_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-phpmyadmin.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-phpmyadmin.tls.certresolver=letsencrypt"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-phpmyadmin.loadbalancer.server.port=80"    

  wordpress:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    hostname: ${COMPOSE_PROJECT_NAME}-app
    image: ${WORDPRESS_IMAGE}:${WORDPRESS_TAG}
    restart: unless-stopped
    depends_on:
      - mariadb
    links:
      - mariadb:mariadb
    volumes:
      - data:/www/wordpress
      - logs:/www/logs
    environment:
      WORDPRESS_DB_HOST: ${COMPOSE_PROJECT_NAME}-mariadb
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${NETWORK}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-wordpress-http.rule=Host(`${SITE_URL}`) || Host(`www.${SITE_URL}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-wordpress-http.entrypoints=web"      
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-wordpress.rule=Host(`${SITE_URL}`) || Host(`www.${SITE_URL}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-wordpress.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-wordpress.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-wordpress.tls.certresolver=letsencrypt"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-wordpress.loadbalancer.server.port=80"          

volumes:
  mariadb:
  data:
  logs:

networks:
  default:
    name: ${NETWORK}
    external: true
