version: '3'

services:
  cadvisor:
    container_name: ${CADVISOR_CONTAINER_NAME}
    image: ${CADVISOR_IMAGE}:${CADVISOR_TAG}
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: always
    privileged: false
    devices:
      - /dev/kmsg
    environment:
      VIRTUAL_HOST: ${SUBDOMAIN}.${DOMAIN},www.${SUBDOMAIN}.${DOMAIN}
      LETSENCRYPT_HOST: ${SUBDOMAIN}.${DOMAIN},www.${SUBDOMAIN}.${DOMAIN}

networks:
  default:
    name: ${NETWORK}
    external: true