version: '3'

services:
  mariadb:
    container_name: ${COMPOSE_PROJECT_NAME}-mariadb
    image: ${MARIADB_IMAGE}:${MARIADB_TAG}
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
    image: ${PHPMYADMIN_IMAGE}:${PHPMYADMIN_TAG}
    restart: always
    depends_on:
      - mariadb
    environment:
      PMA_HOST: ${COMPOSE_PROJECT_NAME}-mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1 # To allow fill db credentials
      VIRTUAL_HOST: ${PHPMYADMIN_DOMAIN}
      LETSENCRYPT_HOST: ${PHPMYADMIN_DOMAIN}

  wordpress:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${WORDPRESS_IMAGE}:${WORDPRESS_TAG}
    restart: unless-stopped
    depends_on:
      - mariadb
    links:
      - mariadb:mariadb
    volumes:
      - site-data:/var/www/wp-content
    environment:
      DB_HOST: ${COMPOSE_PROJECT_NAME}-mariadb
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      #WORDPRESS_SITE_URL: ${WORDPRESS_DOMAIN}
      FS_METHOD: direct
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      VIRTUAL_HOST: ${WORDPRESS_DOMAIN}
      LETSENCRYPT_HOST: ${WORDPRESS_DOMAIN}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://www.${WORDPRESS_DOMAIN}');
        define('WP_SITEURL', 'https://www.${WORDPRESS_DOMAIN}');
        define('WP_ALLOW_MULTISITE', ${WP_ALLOW_MULTISITE});
        define('WP_CACHE', ${WP_CACHE});
        define('WP_REDIS_PREFIX', '${WP_REDIS_PREFIX}');
        define('WP_CACHE_KEY_SALT', '${WP_CACHE_KEY_SALT}');
        define( 'WP_REDIS_HOST', '${WP_REDIS_HOST}');
        define( 'WP_REDIS_PORT', '${WP_REDIS_PORT}');
    logging:
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE}

volumes:
  mariadb:
  site-data:

networks:
  default:
    name: ${NETWORK}
    external: true
