services:
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: ${DATABASE_IMAGE}:${DATABASE_TAG}
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  forgejo:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${FORGEJO_IMAGE}:${FORGEJO_TAG}
    user: 1000:1000
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${FORGEJO_SSH_PORT}:22"
    volumes:
      - data:/data
      - custom:/data/forgejo/custom
      - /etc/localtime:/etc/localtime:ro
    environment:
      USER_UID: 1000
      USER_GID: 1000

      # Custom
      TRYTON_DO_CUSTOM_SYNC_MODE: ${TRYTON_DO_CUSTOM_SYNC_MODE}

      # non-app.ini configuration
      GITEA_WORK_DIR: /data/forgejo
      GITEA_CUSTOM: /data/forgejo/custom
      FORGEJO_WORK_DIR: /data/forgejo
      FORGEJO_CUSTOM: /data/forgejo/custom
      
      # Default
      FORGEJO____APP_NAME: ${APP_NAME}
      FORGEJO____APP_SLOGAN: ${APP_SLOGAN}
      FORGEJO____APP_DISPLAY_NAME_FORMAT: ${APP_NAME}:${APP_SLOGAN}
      
      # Repository
      FORGEJO__repository__DEFAULT_BRANCH: ${DEFAULT_BRANCH}

      # Ui
      FORGEJO__ui__EXPLORE_PAGING_NUM: ${EXPLORE_PAGING_NUM}
      FORGEJO__ui__THEMES: ${THEMES}
      FORGEJO__ui__DEFAULT_THEME: ${DEFAULT_THEME}


      # Server
      FORGEJO__server__DOMAIN: ${FORGEJO_URL}
      FORGEJO__server__ROOT_URL: https://${FORGEJO_URL}
      FORGEJO__server__HTTP_PORT: "3000"
      FORGEJO__server__SSH_PORT: ${FORGEJO_SSH_PORT}
      FORGEJO__server__SSH_LISTEN_PORT: ${FORGEJO_SSH_PORT}

      # Database
      FORGEJO__database__DB_TYPE: ${FORGEJO_DATABASE_DB_TYPE}
      FORGEJO__database__HOST: ${COMPOSE_PROJECT_NAME}-db:3306
      FORGEJO__database__NAME: ${MYSQL_DATABASE}
      FORGEJO__database__USER: ${MYSQL_USER}
      FORGEJO__database__PASSWD: ${MYSQL_PASSWORD}

      # Security
      FORGEJO__security__INSTALL_LOCK: ${INSTALL_LOCK}

      # Service
      FORGEJO__service__ACTIVE_CODE_LIVE_MINUTES: ${ACTIVE_CODE_LIVE_MINUTES}
      FORGEJO__service__RESET_PASSWD_CODE_LIVE_MINUTES: ${RESET_PASSWD_CODE_LIVE_MINUTES}
      FORGEJO__service__REGISTER_EMAIL_CONFIRM: ${REGISTER_EMAIL_CONFIRM}
      FORGEJO__service__DISABLE_REGISTRATION: ${DISABLE_REGISTRATION}
      FORGEJO__service__REQUIRE_SIGNIN_VIEW: ${REQUIRE_SIGNIN_VIEW}
      FORGEJO__service__ENABLE_NOTIFY_MAIL: ${ENABLE_NOTIFY_MAIL}
      FORGEJO__service__ENABLE_CAPTCHA: ${ENABLE_CAPTCHA}
      FORGEJO__service__DEFAULT_ALLOW_CREATE_ORGANIZATION: ${DEFAULT_ALLOW_CREATE_ORGANIZATION}
      FORGEJO__service__NO_REPLY_ADDRESS: ${NO_REPLY_ADDRESS}

      # Mailer
      FORGEJO__mailer__ENABLED: ${FORGEJO_MAILER_ENABLED}
      FORGEJO__mailer__FROM: ${FORGEJO_MAILER_FROM}
      FORGEJO__mailer__PROTOCOL: ${FORGEJO_MAILER_PROTOCOL}
      FORGEJO__mailer__SMTP_ADDR: ${FORGEJO_MAILER_SMTP_ADDR}
      FORGEJO__mailer__USER: ${FORGEJO_MAILER_USER}
      FORGEJO__mailer__PASSWD: ${FORGEJO_MAILER_PASSWD}

      # Cron
      FORGEJO__cron__ENABLED: ${FORGEJO_CRON_ENABLED}
      FORGEJO__cron__SCHEDULE: ${FORGEJO_CRON_SCHEDULE}
      FORGEJO__cron__update_checker__SCHEDULE: ${FORGEJO_CRON_UPDATE_CHECKER_SCHEDULE}
      
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${NETWORK}"
      # Redirecciona HTTP -> HTTPS
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.rule=Host(`${FORGEJO_URL}`) || Host(`www.${FORGEJO_URL}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.middlewares=${COMPOSE_PROJECT_NAME}-https-redirect"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-https-redirect.redirectscheme.scheme=https"
      # HTTPS (con SSL automático)
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${FORGEJO_URL}`) || Host(`www.${FORGEJO_URL}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt"
      # Servicio backend Forgejo
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3000"

volumes:
  db:
  data:
  custom:

networks:
  default:
    name: ${NETWORK}
    external: true
