version: '3'
services:
  wg-easy:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${WIREGUARD_IMAGE}:${WIREGUARD_TAG}
    ports:
      - ${INIT_PORT}:51820/udp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - etc_wireguard:/etc/wireguard
    environment:
      # Optional Configuration
      HOST: ${HOST}
      PORT: ${PORT}
      DISABLE_IPV6: ${DISABLE_IPV6}
      # Unattended Setup
      INIT_ENABLED: ${INIT_ENABLED}
      INIT_USERNAME: ${INIT_USERNAME}
      INIT_PASSWORD: ${INIT_PASSWORD}
      INIT_HOST: ${INIT_HOST}
      INIT_PORT: ${INIT_PORT}      
      INIT_DNS: ${INIT_DNS}
      TZ: ${TZ}
      SERVERURL: ${INIT_HOST}
      INTERNAL_SUBNET: ${INTERNAL_SUBNET}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${NETWORK}"
      # Redirecciona HTTP -> HTTPS
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.rule=Host(`${URL_DOMAIN}`) || Host(`www.${URL_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.middlewares=${COMPOSE_PROJECT_NAME}-https-redirect"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-https-redirect.redirectscheme.scheme=https"
      # HTTPS (con SSL automático)
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${URL_DOMAIN}`) || Host(`www.${URL_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt"
      # Servicio backend WireGuard
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=51821"

volumes:
  etc_wireguard:

networks:
  default:
    name: ${NETWORK}
    external: true