version: '3'
services:
  mariadb:
    container_name: ${COMPOSE_PROJECT_NAME}-mariadb
    image: ${MARIADB_IMAGE}:${MARIADB_TAG}
    restart: always
    volumes:
       - phorge_db:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  phorge:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${PHORGE_IMAGE}:${PHORGE_TAG}
    restart: always
    volumes:
      - phorge_web:/var/www/html
      - phorge_repo:/var/repo
    depends_on:
      - mariadb
    links:
      - mariadb
    ports:
      - ${WEB_PORT}:80
    environment:
      DB_HOST: mariadb
      DB_PORT: ${MYSQL_PORT}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      BASE_URI: https://${URL_DOMAIN}
      PHABRICATOR_ALT_FILE_DOMAIN: https://cdn.${URL_DOMAIN}
      VIRTUAL_HOST: ${URL_DOMAIN},www.${URL_DOMAIN},cdn.${URL_DOMAIN},www.cdn.${URL_DOMAIN}
      LETSENCRYPT_HOST: ${URL_DOMAIN},www.${URL_DOMAIN},cdn.${URL_DOMAIN},www.cdn.${URL_DOMAIN}

volumes:
  phorge_web:
  phorge_repo:
  phorge_db:

networks:
  default:
    name: ${NETWORK}
    external: true
