version: '3'

services:
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    image: ${MYSQL_IMAGE}:${MYSQL_TAG}
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQL_PORT}:3306 

  gitea:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${GITEA_IMAGE}:${GITEA_TAG}
    restart: always
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "${GITEA_PORT}:3000"
      - "${GITEA_SSH_PORT}:22"
    expose:
      - "${GITEA_PORT}:3000"
      - "${GITEA_SSH_PORT}:22"
    volumes:
      - data:/var/lib/gitea
      - config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      GITEA__database__DB_TYPE: mysql
      GITEA__database__HOST: ${COMPOSE_PROJECT_NAME}-mysql:${MYSQL_PORT}
      GITEA__database__NAME: ${MYSQL_DATABASE}
      GITEA__database__USER: ${MYSQL_USER}
      GITEA__database__PASSWD: ${MYSQL_PASSWORD}
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: ${DOMAIN},www.${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN},www.${DOMAIN}

volumes:
  db:
  data:
  config:

networks:
  default:
    name: ${NETWORK}
    external: true
