version: '3'
services:
  openldap:
    container_name: ${COMPOSE_PROJECT_NAME}-openldap
    image: ${LDAP_IMAGE}:${LDAP_TAG}
    restart: always
    hostname: ${LDAP_HOSTNAME}
    environment:
      HOSTNAME: ${LDAP_HOSTNAME}
      LDAP_ORGANISATION: ${LDAP_ORGANISATION}
      LDAP_DOMAIN: ${LDAP_DOMAIN}
      LDAP_BINDDN: ${LDAP_BINDDN}
      LDAP_SECRET: ${LDAP_SECRET}
      VIRTUAL_HOST: ${LDAP_HOSTNAME}
      LETSENCRYPT_HOST: ${LDAP_HOSTNAME}
    ports:
      - ${LDAP_PORT}:389
      - ${LDAPS_PORT}:636
    volumes:
      - config:/etc/ldap/slapd.d
      - ssl:/etc/ldap/ssl
      - database:/var/lib/ldap
      - tmp:/run/slapd

  phpldapadmin:
    container_name: ${COMPOSE_PROJECT_NAME}-phpldapadmin
    image: ${PHPLDAPADMIN_IMAGE}:${PHPLDAPADMIN_TAG}
    restart: always
    depends_on:
      - openldap
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ${LDAP_HOSTNAME}
      PHPLDAPADMIN_HTTPS: false
      VIRTUAL_HOST: ${PHPLDAPADMIN_URL}
      LETSENCRYPT_HOST: ${PHPLDAPADMIN_URL}

volumes:
  config:
  ssl:
  database:
  tmp:

networks:
  default:
    name: ${NETWORK}
    external: true