version: '3'
services:
  openldap:
    container_name: ${LDAP_CONTAINER_NAME}
    image: ${LDAP_IMAGE}:${LDAP_TAG}
    restart: always
    hostname: ${LDAP_HOSTNAME}
    environment:
      HOSTNAME: ${LDAP_HOSTNAME}
      LDAP_ORGANISATION: ${LDAP_ORGANISATION}
      LDAP_DOMAIN: ${LDAP_DOMAIN}
      LDAP_BASE_DN: ${LDAP_BASE_DN}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_CONFIG_PASSWORD: ${LDAP_CONFIG_PASSWORD}
      VIRTUAL_HOST: ${LDAP_HOSTNAME}
      LETSENCRYPT_HOST: ${LDAP_HOSTNAME}
    ports:
      - ${LDAP_PORT}:389
      - ${LDAPS_PORT}:636

  phpldapadmin:
    container_name: ${PHPLDAPADMIN_CONTAINER_NAME}
    image: ${PHPLDAPADMIN_IMAGE}:${PHPLDAPADMIN_TAG}
    restart: always
    depends_on:
      - openldap
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: |
        - ${LDAP_HOSTNAME}:
      PHPLDAPADMIN_HTTPS: false
      VIRTUAL_HOST: ${PHPLDAPADMIN_URL}
      LETSENCRYPT_HOST: ${PHPLDAPADMIN_URL}

volumes:
  data:

networks:
  default:
    name: ${NETWORK}
    external: true