version: '3'
services:
  openldap:
    container_name: ${LDAP_CONTAINER_NAME}
    image: ${LDAP_IMAGE}:${LDAP_TAG}
    restart: always
    hostname: ${LDAP_HOSTNAME}
    environment:
      LDAP_ROOT: ${LDAP_ROOT}
      LDAP_ADMIN_USERNAME: ${LDAP_ADMIN_USERNAME}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_CONFIG_ADMIN_ENABLED: ${LDAP_CONFIG_ADMIN_ENABLED}
      LDAP_CONFIG_ADMIN_USERNAME: ${LDAP_CONFIG_ADMIN_USERNAME}
      LDAP_CONFIG_ADMIN_PASSWORD: ${LDAP_CONFIG_ADMIN_PASSWORD}
      LDAP_USERS: ${LDAP_USERS}
      LDAP_PASSWORDS: ${LDAP_PASSWORDS}
      LDAP_USER_DC: ${LDAP_USER_DC}
      LDAP_GROUP: ${LDAP_GROUP}
      LDAP_ADD_SCHEMAS: ${LDAP_ADD_SCHEMAS}
      LDAP_EXTRA_SCHEMAS: ${LDAP_EXTRA_SCHEMAS}
      LDAP_SKIP_DEFAULT_TREE: ${LDAP_SKIP_DEFAULT_TREE}
      LDAP_CUSTOM_LDIF_DIR: ${LDAP_CUSTOM_LDIF_DIR}
      LDAP_CUSTOM_SCHEMA_FILE: ${LDAP_CUSTOM_SCHEMA_FILE}
      LDAP_CUSTOM_SCHEMA_DIR: ${LDAP_CUSTOM_SCHEMA_DIR}
      LDAP_ULIMIT_NOFILES: ${LDAP_ULIMIT_NOFILES}
      LDAP_ALLOW_ANON_BINDING: ${LDAP_ALLOW_ANON_BINDING}
      LDAP_LOGLEVEL: ${LDAP_LOGLEVEL}
      LDAP_PASSWORD_HASH: ${LDAP_PASSWORD_HASH}
      LDAP_CONFIGURE_PPOLICY: ${LDAP_CONFIGURE_PPOLICY}
      LDAP_PPOLICY_USE_LOCKOUT: ${LDAP_PPOLICY_USE_LOCKOUT}
      LDAP_PPOLICY_HASH_CLEARTEXT: ${LDAP_PPOLICY_HASH_CLEARTEXT}
      LDAP_ENABLE_ACCESSLOG: ${LDAP_ENABLE_ACCESSLOG}
      LDAP_ACCESSLOG_ADMIN_USERNAME: ${LDAP_ACCESSLOG_ADMIN_USERNAME}
      LDAP_ACCESSLOG_ADMIN_PASSWORD: ${LDAP_ACCESSLOG_ADMIN_PASSWORD}
      LDAP_ACCESSLOG_DB: ${LDAP_ACCESSLOG_DB}
      LDAP_ACCESSLOG_LOGOPS: ${LDAP_ACCESSLOG_LOGOPS}
      LDAP_ACCESSLOG_LOGSUCCESS: ${LDAP_ACCESSLOG_LOGSUCCESS}
      LDAP_ACCESSLOG_LOGPURGE: ${LDAP_ACCESSLOG_LOGPURGE}
      LDAP_ACCESSLOG_LOGOLD: ${LDAP_ACCESSLOG_LOGOLD}
      LDAP_ACCESSLOG_LOGOLDATTR: ${LDAP_ACCESSLOG_LOGOLDATTR}
      LDAP_ENABLE_SYNCPROV: ${LDAP_ENABLE_SYNCPROV}
      LDAP_SYNCPROV_CHECKPPOINT: ${LDAP_SYNCPROV_CHECKPPOINT}
      LDAP_SYNCPROV_SESSIONLOG: ${LDAP_SYNCPROV_SESSIONLOG}
      LDAP_ENABLE_TLS: ${LDAP_ENABLE_TLS}
      LDAP_REQUIRE_TLS: ${LDAP_REQUIRE_TLS}
      LDAP_ADMIN_DN: cn=${LDAP_ADMIN_USERNAME},${LDAP_ROOT}
      VIRTUAL_HOST: ${LDAP_HOSTNAME},www.${LDAP_HOSTNAME}
      LETSENCRYPT_HOST: ${LDAP_HOSTNAME},www.${LDAP_HOSTNAME}
    volumes:
      - openldap_data:/bitnami/openldap
    ports:
      - ${LDAP_PORT_NUMBER}:389
      - ${LDAP_LDAPS_PORT_NUMBER}:636

  phpldapadmin:
    container_name: ${PHPLDAPADMIN_CONTAINER_NAME}
    image: ${PHPLDAPADMIN_IMAGE}:${PHPLDAPADMIN_TAG}
    restart: always
    depends_on:
      - openldap
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: false
      VIRTUAL_HOST: ${PHPLDAPADMIN_URL},www.${PHPLDAPADMIN_URL}
      LETSENCRYPT_HOST: ${PHPLDAPADMIN_URL},www.${PHPLDAPADMIN_URL}

volumes:
  openldap_data:

networks:
  default:
    name: ${NETWORK}
    external: true