services:
  gitlab-runner:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: heptapod/heptapod-runner:${HEPTAPOD_CE_RUNNER_TAG}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - heptapod-runner-config:/etc/heptapod-runner/
      - heptapod-runner-cache:/cache
    environment:
      TZ: ${TZ}
      
volumes:
  heptapod-runner-config:
  heptapod-runner-cache:

networks:
  default:
    name: ${NETWORK}
    external: true
