version: '3'

services:
  gitlab-ce-runner:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: gitlab/gitlab-runner:${GITLAB_CE_RUNNER_TAG}
    restart: always
    volumes:
      - config:/etc/gitlab-runner/
      - /var/run/docker.sock:/var/run/docker.sock
      - cache:/cache
    environment:
      TZ: ${TZ}
      
  gitlab-ce-runner-register:
    container_name: ${COMPOSE_PROJECT_NAME}-register
    restart: 'no'
    image: gitlab/gitlab-runner:${GITLAB_CE_RUNNER_TAG}
    depends_on:
      - gitlab-ce-runner
    environment:
      TZ: ${TZ}
      CI_SERVER_URL: ${CI_SERVER_URL}
      REGISTRATION_TOKEN: ${REGISTRATION_TOKEN}
    command:
      - register
      - --non-interactive
      - --locked=false
      - --name=${GITLAB_CE_RUNNER_NAME}
      - --executor=docker
      - --docker-image=docker:${DOCKER_TAG}
      - --docker-volumes=/var/run/docker.sock:/var/run/docker.sock
      - --run-untagged="true"
      - --docker-image alpine:latest
      - --description "docker-runner"
      - --tag-list "privileged"
      - --access-level="not_protected"
    volumes:
      - config:/etc/gitlab-runner/
      
volumes:
  config:
  cache:

networks:
  default:
    name: ${NETWORK}
    external: true
